### ISSUE TITLE
Collider issue, part FASAApolloIU

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/FASA-RO#1]
The pads of the landing legs on the LEM intentionally come down into the hollow space that should exist on this part. When that is done, issues occur. When the LEM is separated from the fully constructed Apollo - Saturn V it jumps violently away and sometimes a part explodes off.

The FASAApolloIU should have a hollow space in the visually hollow portion in the middle, but currently does not.

**Comment by raidernick** [comment]
this is fixed
