### ISSUE TITLE
LR91 Refuses to shut off

### ISSUE THREAD

**Issue by That-Ben-Guy** [KSP-RO/FASA-RO#10]
As the title says, the LR91 is kind of acting like an SRB once ignited. Throttling to zero will not shut it off. The only way I've been able to turn this engine off is by locking the fuel tanks. And, once you unlock them again, the engine fires back up until it's run out of propellant, regardless of whether the throttle is set to on or off. I had a look over the configs, but I couldn't see anything obvious that might be responsible.

**Comment by stratochief66** [comment]
@KalynnDarcy 

Could you share your module manager config for this part, from your module manager log? Pastebin or whatever tool for sharing will suffice.

**Comment by raidernick** [comment]
Cannot reproduce, had other users try to also, no success. Must be user error.
