### ISSUE TITLE
This does not show up on CKAN as 1.2.2 compatible - on purpose? 

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/FASA-RO#12]
Version 7.0. does not show up on CKAN. Is that a bug or on purpose?

**Comment by glilienthal** [comment]
To be more precise: It does show up in CKAN, but still gives compatibilty 1.0.5

**Comment by stratochief66** [comment]
I don't really muck with CKAN. I've clearly labelled this version as KSP 1.2.2 compatible. Anyone is free to interact with CKAN to let it know this version is compatible as labelled.

If you (or anybody know), would it simply be easiest for this repo to have a CKAN pointing file, like so? Is that a sufficient or necessary step?
https://github.com/KSP-RO/RealismOverhaul/blob/master/RealismOverhaul.netkan

**Comment by glilienthal** [comment]
Hm. Strange. When I look at https://github.com/KSP-CKAN/CKAN-meta/blob/master/FASA/FASA-v7.0.ckan it clearly says 1.2.0 - 1.2.2. I'll ask in ckan.
