### ISSUE TITLE
Remote Tech with FASA

### ISSUE THREAD

**Issue by rottielover** [KSP-RO/FASA-RO#13]
Here is a note and response I put on the official KSP forums...  Can anyone here help??

  22 hours ago
Could someone point me in the correct direction?   I installed RT via ckan, and FASA, but none of the FASA antenna's work with Remote Tech.  Is there a MM patch someplace for this?

The RT mod has its two own MM patches for FASA, RemoteTech_FASA_Antennas.cfg and RemoteTech_FASA_Probes.cfg, which should work on your computer. But they are last updated in 2015 and I see the FASA mod is not updated since KSP 1.0, besides the community patches supplied. You may want to post a question to the FASA thread to ask about any recent change in community FASA patches prevent the RT's FASA patches from working.

**Comment by PhineasFreak** [comment]
Some questions:

* Do you have any log files to provide?
* Did you verify that the MM patches are getting applied?
* Did you test the FASA/RT interop by manually installing the mods? CKAN can really screw things up sometimes.
* Do the patches work in a clean KSP installation with only these mods installed?

**Comment by rottielover** [comment]
1 - didn't bundle up anything but if you want them I can get them too you somehow.  Just tell me what files you want,.

2- I think they are, cause when you activate the antenna it shows power consumption and distance , but only power consumption changes when the ant. is activated, it never displays the distance and RT doesn't make the connection.

3 - I removed the ckan ones , downloaded and installed by hand and same result

4 - I'll try that next.

**Comment by PhineasFreak** [comment]
Let's start with the basic "**KSP.log**" file (under your KSP installation folder) and work from there.
