### ISSUE TITLE
Collider issue, part FASAExplorerSgt11

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/FASA-RO#2]
When this part is expended and is staged off of a Juno-Explorer launch, the remaining upper stage parts (the FASAExplorerSgt3 nests inside of this part) are violently shunted.

This suggests that the collider inside the FASAExplorerSgt11 part is not hollow as it would need to be in order for the FASAExplorerSgt3 to sit inside it comfortably and stage away.

There is a chance the issue is also with one of the other related parts in this situation, such as the FASAExplorerSgt11Dec.

**Comment by raidernick** [comment]
I know the issue with this already I had to fix it for the copy of these parts I included with my Juno II rocket. I made some modifications to the mesh and texture for my purposes but I can apply to same fix again to the original part no problem

**Comment by raidernick** [comment]
Ok so these are fixed, I will just copy the model files over I modified
