### ISSUE TITLE
Errors in loading and MM processing

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/FASA-RO#26]
For a long time FASA spams me with a good amount of soft errors on load.  Cleaning them up should be a good thing as most of them are simple texture issues.

This is an example of those errors from a Clean 1.2.2+FASA/MM only load. 

-Texture load errors are probably more important than the "not Found" errors but both need addressing
-The failed to create errors look like the .dds needs to be reprocessed. 
all the files apear to exist and load in GIMP for me.  It could be that they just need mipmaps generated properly or some other minor .dds nuance.

`	Line 413: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Apollo\ApolloCSM\ColorRed.dds'
	Line 421: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Apollo\ApolloCSM\ColorWhite.dds'
	Line 429: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Apollo\ApolloCSM\ColorWhiteDark.dds'
	Line 441: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Apollo\ApolloCSM\ColorYellow.dds'
	Line 1435: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\ASETindicators\model000.dds'
	Line 1467: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\Bolt\BoltCap.dds'
	Line 1475: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\Bolt\BoltCap_NRM.dds'
	Line 1727: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\LM_FuelIndicatorSE\FuelIndicatorInd.dds'
	Line 1739: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\LM_FuelIndSE\FuelIndicatorInd.dds'
	Line 1915: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\LM_Mirror\screen-emissive.dds'
	Line 1923: Texture load error in 'G:\SteamLibrary\steamapps\common\KSP 1.2.2 Clean\GameData\FASA\Props\LM_Mirror\screen.dds'
	Line 15061: ERROR: no sound file found for sound_Titan_srb
	Line 15077: ERROR: no sound file found for sound_Titan_srb

d3d11: failed to create staging 2D texture w=16 h=10 d3dfmt=77 [80070057]
d3d11: failed to create staging 2D texture w=8 h=5 d3dfmt=77 [80070057]
Load(Texture): FASA/Agencies/FASA_scaled

d3d11: failed to create staging 2D texture w=16 h=10 d3dfmt=77 [80070057]
d3d11: failed to create staging 2D texture w=8 h=5 d3dfmt=77 [80070057]
Load(Texture): FASA/Flags/FASA_Rescue

d3d11: failed to create staging 2D texture w=16 h=10 d3dfmt=71 [80070057]
d3d11: failed to create staging 2D texture w=8 h=5 d3dfmt=71 [80070057]
Load(Texture): FASA/Flags/FASA_USA50

d3d11: failed to create staging 2D texture w=16 h=10 d3dfmt=71 [80070057]
d3d11: failed to create staging 2D texture w=8 h=5 d3dfmt=71 [80070057]
Load(Texture): FASA/FX/rocketplume2

	Line 5379: Texture 'FASA/Apollo/ApolloCSM/FoilBlack' not found!
	Line 5383: Texture 'FASA/Apollo/ApolloCSM/RCS_box_NRM' not found!
	Line 5391: Texture 'FASA/Apollo/ApolloCSM/ColorWhite' not found!
	Line 5395: Texture 'FASA/Apollo/ApolloCSM/FoilWhite' not found!
	Line 5399: Texture 'FASA/Apollo/ApolloCSM/ColorRed' not found!
	Line 5403: Texture 'FASA/Apollo/ApolloCSM/ColorYellow' not found!
	Line 5407: Texture 'FASA/Apollo/ApolloCSM/4bolts' not found!
	Line 5411: Texture 'FASA/Apollo/ApolloCSM/4bolts_NRM' not found!
	Line 5423: Texture 'FASA/Apollo/ApolloCSM/FoilWhite' not found!
	Line 5427: Texture 'FASA/Apollo/ApolloCSM/FoilGold' not found!
	Line 5435: Texture 'FASA/Apollo/ApolloCSM/FoilWhite' not found!
	Line 5439: Texture 'FASA/Apollo/ApolloCSM/FoilGold' not found!
	Line 5443: Texture 'FASA/Apollo/ApolloCSM/FoilBlack' not found!
	Line 5447: Texture 'FASA/Apollo/ApolloCSM/ColorYellow' not found!
	Line 5455: Texture 'FASA/Apollo/ApolloCSM/FoilWhite' not found!
	Line 5459: Texture 'FASA/Apollo/ApolloCSM/wall1_DIFFUSE' not found!
	Line 5463: Texture 'FASA/Apollo/ApolloCSM/wall1_nrm' not found!
	Line 5471: Texture 'FASA/Apollo/ApolloCSM/RCS_box_NRM' not found!
	Line 5475: Texture 'FASA/Apollo/ApolloCSM/ColorYellow' not found!
	Line 5479: Texture 'FASA/Apollo/ApolloCSM/rusty' not found!
	Line 5515: Texture 'FASA/Apollo/ApolloCSM/Apollo_CSM_n' not found!
	Line 5559: Texture 'FASA/Apollo/FASA_Apollo_Str/LFT_S1B_Stage1_n' not found!
	Line 5823: Texture 'FASA/Gemini2/FASA_Gemini_Engine_Fuel2/Gemini_RCSFuel_Pack' not found!
	Line 5927: Texture 'FASA/Gemini2/FASA_Gemini_LR91_Pack/LFT_Fairing_n' not found!
	Line 6367: Texture 'FASA/Props/ASETindicators/model000' not found!
	Line 6387: Texture 'FASA/Props/Bolt/BoltCap' not found!
	Line 6391: Texture 'FASA/Props/Bolt/BoltCap_NRM' not found!
	Line 6471: Texture 'FASA/Props/LM_CompDisplay/GrayLight' not found!
	Line 6503: Texture 'FASA/Props/LM_FuelIndicatorSE/FuelIndicatorInd' not found!
	Line 6511: Texture 'FASA/Props/LM_FuelIndSE/FuelIndicatorInd' not found!
	Line 6579: Texture 'FASA/Props/LM_Mirror/screen' not found!
	Line 6583: Texture 'FASA/Props/LM_Mirror/screen-emissive' not found!

Load(Model): FASA/Gemini2/FASA_Gemini_SAS_RCS/Gemini_Utility_SasRcs
	Line 6063: Triggers on concave MeshColliders are not supported x6

	Line 5663: WheelCollider requires an attached Rigidbody to function.
	`

**Comment by Bornholio** [comment]
Did a trial with ColorYellow.dds imported in GIMP, then exported with DXT5 and export Mipmaps options.
This removed the error from the log

**Comment by Bornholio** [comment]
went through all the "Texture load error" parts and reencoded, fixing those errors and related "not Found!" errors.  Coppied several textures from other locations in file structure to ApolloCSM folder to fix most of the remaining problems.

**Comment by Bornholio** [comment]
https://github.com/KSP-RO/FASA-RO/pull/27

**Comment by raidernick** [comment]
merged
