### ISSUE TITLE
Can't pick up the Baby Sergeant 11x Cluster Decoupler once placed

### ISSUE THREAD

**Issue by Vermoot** [KSP-RO/FASA-RO#29]
Whether placed on another part or anywhere in the VAB (outlined red), there is no way to pick the part up to move it or delete it. Same with the move tool, rotate tool, and reroot tool. Hovering on the part (anywhere) doesn't show a tooltip.

**Comment by raidernick** [comment]
fixed: https://github.com/KSP-RO/FASA-RO/commit/7418d8f1bcd543f7a820afb3bd698f9fad87a55f
