### ISSUE TITLE
FASA Apollo Saturn V / Launch Pad Problems

### ISSUE THREAD

**Issue by gamerscircle** [KSP-RO/FASA-RO#3]
I have KSP 1.1.2 installed and I have downloaded and installed the FASA mod that is currently available.   I have removed the GameData/Plugins/ReflectionPlugin.dll

1.) Load in FASA Apollo Saturn V.craft into Vab
2.) Press the Launch button
3.) In or around the LEM area, there is massive explosion and the craft will wip around.  Resulting in the LEM being tossed from the rocket.

Screenshots have been upload to help illustrate and perhaps explain what happened?

![screenshot32](https://cloud.githubusercontent.com/assets/17105937/15087244/04886e68-139c-11e6-8974-664cb6cf1daa.png)
![screenshot33](https://cloud.githubusercontent.com/assets/17105937/15087246/07fd4d70-139c-11e6-98cc-926c69d55a55.png)

**Comment by raidernick** [comment]
The instrument unit(the black ring on the SIVB) is broken since KSP 1.0, the issue has already been reported and I know how to fix it. The other issue is here: https://github.com/KSP-RO/FASA-RO/issues/1

**Comment by stratochief66** [comment]
There is no release version of RO or or FASA for 1.1 yet. As raidernick says, there are known issues with the parts under 1.1 and that is why they haven't seen a 1.1 release yet.

**Comment by NathanKell** [comment]
@stratochief66 Raidernick did specifically ask people in the FASA thread to post here with the specific parts they have problems with, so he would know which still need fixing.
