### ISSUE TITLE
Atlas Decoupler reflective material missing

### ISSUE THREAD

**Issue by droric** [KSP-RO/FASA-RO#34]
The Atlas engine decoupler does not have a reflective material while the tanks are metallic chrome.

![image](https://user-images.githubusercontent.com/5543338/46326599-7cf0f800-c5cb-11e8-95f4-0bf2438245f5.png)

**Comment by PhineasFreak** [comment]
While the skirt was a bit reflective, the effect was not as pronounced as the rest of the booster: https://www.flickr.com/photos/sdasmarchives/15902587600/in/album-72157649485000247

Maybe a bump in the specularity will be enough?

**Comment by raidernick** [comment]
it's not missing, it's not supposed to be reflective like the main tank

**Comment by droric** [comment]
> While the skirt was a bit reflective, the effect was not as pronounced as the rest of the booster: https://www.flickr.com/photos/sdasmarchives/15902587600/in/album-72157649485000247
> 
> Maybe a bump in the specularity will be enough?

A small bump in specularity would make it look better in my opinion.  It looks out of place compared to the gleaning tank section.
