### ISSUE TITLE
Apollo/LEM tunnel

### ISSUE THREAD

**Issue by AnalogEdition** [KSP-RO/FASA-RO#35]
With the change to openning the LEM hatch via IVA, there is an unwanted interaction with CLS. The crew tunnel acces (xfer) to the LEM is unavailable without first having to EVA from the CM then  entering the LEM to open the hatch. 

Seems odd to have to enter the craft in order to open the hatch to be able to then, enter the craft.

**Comment by Acebking665** [comment]
When I try to get in the LEM it wont let me i have seen a video that someone clicks a button inside but idk where

**Comment by raidernick** [comment]
You need Raster Prop Monitor to open the hatch and you do it by clicking the yellow handle on the door in the LEM iva.

**Comment by AnalogEdition** [comment]
Has the original issue been resolved? The original issue is that after transposition, docking and extraction, in order for the crew to use the tunnel to access the lem they need to open the csm hatch via iva as you mention above, they then need to eva, enter the lem through the front hatch and the iva to open the tunnel hatch. It makes the tunnel virtually pointless as you have to eva from csm to lem to open the lem hatch.
