### ISSUE TITLE
Collider issue, part FairingWall3m

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/FASA-RO#4]
This is used to make the LMA (Saturn V adapter) part. You (raidernick) already fixed it for us, it hasn't been part of a release yet.

https://www.dropbox.com/s/mslc0tslr0bzc5u/FairingWall3m.mu?dl=0

**Comment by raidernick** [comment]
Is this already included in the git here? If not can you PR it.

**Comment by stratochief66** [comment]
I don't see any parts as I recognize them in this repo. The closest I see to a what I recognize is here, and it is substantially different from an actual FASA download.
https://github.com/KSP-RO/FASA-RO/tree/master/Source/Unity%20Projects/FASA_SHARE/Assets

**Comment by raidernick** [comment]
I forgot I never actually uploaded the actual mod just the source. Can you take a snapshot of your "best" working version of FASA that you have and make a PR for it into the gamedata folder, minus the plugin that I'm removing from there now.

**Comment by stratochief66** [comment]
@raidernick 

Looks like @NathanKell was able to upload this (Thanks!)

**Comment by raidernick** [comment]
@NathanKell did you add this part with the copy you uploaded? I don't have it anymore myself? Is this good to close?
