### ISSUE TITLE
 RSS RO a realchute doesn't work on parachutes ?

### ISSUE THREAD

**Issue by SergAfan1983** [KSP-RO/FASA-RO#44]

**Comment by raidernick** [comment]
this means nothing, why are you putting a realchute chute on the existing chute? why aren't you just using the normal chute? there is nothing wrong with the fasa chutes in RO if everything is installed correctly. I won't provide you support with RO here so don't ask.

**Comment by SergAfan1983** [comment]
specie, parachute a FASA mercury non opus est, cum realchut ,capsulam frangit in terram ad velocitatem 100 m/s .omnes mods sunt velit, tincidunt et hoc problema non nisi in me
