### ISSUE TITLE
Collider issue, part FASAApollo_CM_Decoupler

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/FASA-RO#5]
the CM pops off with substantial unexpected force that isn't accounted for in any of the associated parts. 

Seems to be a collider issue with concavity like the other parts I've mentioned here.

**Comment by raidernick** [comment]
I actually let frizzank know about this issue over a year ago, and he had fixed it. The collider was actually convex and shouldn't have been, before 1.0. The last time I used FASA it worked still, maybe he accidentally put the bad file in his latest release again.

**Comment by raidernick** [comment]
should be fixed now
