### ISSUE TITLE
Multiple issues: FASAGeminiBigGDockExt

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/FASA-RO#6]
The Big Gemini Docking Ring has multiple problems basically making it unusable:
1. With the way it is gendered, the only part I could find that it would mate to is the port built into the Apollo LEM.  It should either be made non-gendered, or an appropriate male station part needs to be added.
2. When you select "control from here" on the part, your forward axis is not lined up with the docking axis, but instead is perpendicular, eg "up" in terms of the capsule, instead of "to the rear" as would be correct.
3. When you open mechjeb docking autopilot or the docking port alignment indicator mods, they insist that you must select a docking port as the control point, even when the Big Gemini Docking Ring is selected, they do not recognize the part as being a docking port.

**Comment by stratochief66** [comment]
Thanks for the solid issue description @dgeastman. We've discussed it a few times in the #RO IRC, so we are aware.

I'm not aware if anybody is taking on the challenge of trying to figure out a config fix yet though.

**Comment by raidernick** [comment]
@stratochief66 if it is a problem with the transform in the model I can easily fix it. If it's a config issue, someone who does the config work for FASA will need to look at it. I know you did some work on the configs, or maybe ask whoever was also helping you to take a look at them if that's the case.

**Comment by raidernick** [comment]
What is the status of this?

**Comment by dgeastman** [comment]
As far as I know, there has been no work on this.  I wouldn't know where to begin, myself.

**Comment by stratochief66** [comment]
Still a known and described problem, nobody working to fix it currently.

@dgeastman , did you make those observations in stock KSP, or KSP with RSS/RO?

**Comment by dgeastman** [comment]
This was in RSS/RO

**Comment by raidernick** [comment]
Since this is an RO issue I copied this issue to there since it is still ongoing: https://github.com/KSP-RO/RealismOverhaul/issues/1831
