### ISSUE TITLE
Issues as of PR #8

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/FASA-RO#9]
Noting down issues I noticed while testing the version on PR #8, within RO (current Github version) in KSP 1.2.2

RN, if any of these issues are ones that will need to be addressed with RO patch changes, please let me know, and I will move them to an Issue over there. I may still need your insight to figure out what is causing the issue though.

Issue A
The Explorer 3x sergeant doesn't decouple smoothly from the 11x sergeant. may be a collider issue still exists in one of those parts, or in the decoupler part itself. 
Current Status: Just looking for someone else to test and confirm this.

Issue B
All collider issues appear to be gone, I can now build the Saturn V with the LEM with no collision at all.
The base the LEM sits in doesn't currently have a stageable decouple, but can be right clicked to decouple.

Issue C
The LEM base when decoupled (through the right click menu) lets the LEM go, but doesn't seem to have an option to separate from the CSM. IIRC, the stag-able decoupler for the LEM base was previously what did this.

Issue D
The 4 covers that sit between the LEM base and the CSM do not appear to detach when staged. If it was just a decoupler 'engine' problem, I'd expect them to separate but not move away. Here, they seem rigidly attached.

**Comment by raidernick** [comment]
@stratochief66 the sergeants are still broken definitely and I need to fix them. As for all the lem/csm decoupler problems, that looks like an issue with the changes jebs made to the config files and needs to be fixed. I can fix the colliders can you see if you can make some changes to the config to get the parts separating correctly and let me know if it's fixable like that?

**Comment by stratochief66** [comment]
Yep, I'll look into that. Hopefully I have time tomorrow, otherwise it might be a while before I can look.

**Comment by stratochief66** [comment]
D just seemed to resolve itself, and I found the solution for B & C and added it to the open PR on FASA-RO

**Comment by Roccoriu** [comment]
By the way... I cannot use the LEM legs properly and I cannot exit the LEM either. Did you fix that already?

**Comment by stratochief66** [comment]
Lunar legs fold out properly with the last PR in.
Note the use of the generic module.
https://github.com/KSP-RO/FASA-RO/blob/2b995ed20dd5cd58e61aabe57e60e52a39526595/GameData/FASA/Apollo/LEM/LandingLegs/LM_LandingLeg.cfg#L77

@raidernick the legs, upon landing, never touch down and float above the ground frictionless. Same occurs with both the legs with the contact probe, and the set with the ladder. That is something we'll need to track someone down to change the model for, correct?

**Comment by raidernick** [comment]
@stratochief66 have you had time to test with the fixes mentioned in that post on the forums regarding RPM and the legs?

**Comment by stratochief66** [comment]
I tried it in 1.1.3, no luck. I must have something else wrong/funky.

**Comment by dennislee9999** [comment]
I am using current version of FASA with RO, and when i tried to launch Juno 1 or Atlas, the engine seems not RO patched or something. Thrust is not right.

**Comment by stratochief66** [comment]
@dennislee9999 they perhaps you're using the not mutually compatible versions of the two, or another mod like RF. Apologies, but this is not the place to request support.

**Comment by stratochief66** [comment]
Works fine for me in 1.2 though. And the rest of the changes discussed here have been tested and merged, I think, so closing.
